" OS configuration
runtime! archlinux.vim

" Color
if has("syntax")
	syntax on
endif

if has("autocmd")
	filetype plugin indent on
endif

" Global configuration
set background=dark                  " Adapt colors to a dark background
set mouse=a                          " Enable use of mouse
set autoindent                       " Keep indent on new lines
set number                           " Print line numbers
set tabstop=4 shiftwidth=4 expandtab " Use 4 spaces instead of tabs
set hlsearch                         " Highlight search results
set incsearch                        " start searching while typing
set ignorecase                       " Ignore case ...
set smartcase                        " ... unless there is at least one maj
set listchars+=nbsp:.                " Show unbreacable spaces in list mode
set modeline                         " Read preferences integrated in files

" Doxygen coloration for files
au BufNewFile,BufRead *.doxygen setfiletype doxygen
au BufNewFile,BufRead *.dox setfiletype doxygen

" Tex coloration for class syntax
au BufNewFile,BufRead *.cls set ft=tex

" Txt2tags coloration
au BufNewFile,BufRead *.t2t set ft=txt2tags

" PDE (arduino IDE files) coloration
au BufNewFile,BufRead *.pde set ft=cpp
au BufNewFile,BufRead *.ino set ft=cpp

" GLSL coloration
au BufNewFile,BufRead *.frag,*.vert,*.glsl set ft=glsl

" FakeFS coloration
au BufNewFile,BufRead *.fakefs set ft=fakefs

" Syntax check ...
setlocal spell spelllang=fr,en
" ... disabled by default
set nospell

" LaTeX shortcuts
au BufNewFile,BufRead *.tex iab bi \begin{itemize}
au BufNewFile,BufRead *.tex iab ei \end{itemize}
au BufNewFile,BufRead *.tex iab st \section
au BufNewFile,BufRead *.tex iab sst \subsection
au BufNewFile,BufRead *.tex iab ssst \subsubsection

" MSMTP config syntax coloration
au BufNewFile,BufRead .msmtprc set ft=msmtp

" Completion configuration.
set completeopt=longest,menuone
imap <tab> <C-X><C-U>

" Address completion with mutt
au BufRead /tmp/mutt* source ~/.mutt/address-search.vim

" Autocomplete popup window colors
highlight clear
highlight Pmenu      ctermfg=7 ctermbg=4
highlight PmenuSel   ctermfg=0 ctermbg=7
highlight PmenuSbar  ctermfg=7 ctermbg=0
highlight PmenuThumb ctermfg=0 ctermbg=7


" TagList configuration
let Tlist_Exit_OnlyWindow=1                     " Exit when the TagList window is the last one.
let tlist_txt2tags_settings='txt2tags;d:Titles' " Using txt2tags with taglist

" Using system clipboard
vmap <C-y> :!xclip -f <CR>
map <C-p> :r !xclip -o<CR>

