# Starting tmux
/home/LOG1/Prog/tmux-nsession.sh default

# History configuration
HISTFILE=~/.histfile
HISTSIZE=2000
SAVEHIST=2000

# Handle ST
function zle-line-init() { echoti smkx }
function zle-line-finish() { echoti rmkx }
zle -N zle-line-init
zle -N zle-line-finish

# Global settings
setopt appendhistory autocd extendedglob
unsetopt beep notify nomatch
bindkey -e

# Style
zstyle :compinstall filename '/home/LOG1/.zshrc'
zstyle ':completion:*' menu select

# Prompt
autoload -U promptinit
promptinit

plugins=(git)
ZSH_THEME=fox
ZSH=/usr/share/oh-my-zsh/
source $ZSH/oh-my-zsh.sh

# Completion
autoload -Uz compinit
compinit
# Don't autocomplete twice for rm
zstyle ':completion:*:rm:*' ignore-line yes
# pass completion
source ~/.zsh/pass.zsh-completion

# Aliases
alias ls='ls --color=auto'
alias ll='ls -lrthF'
alias lla='ll -A'
alias llp='ll *.{c,h}pp'
alias llc='ll *.{c,h}'
alias lldev='ll /dev/sd*'
alias lld='lldev'
alias rm='rm --preserve-root -i'
alias nmap='nmap -T4 -A -v'
alias gitrlg='git log --pretty=format:"%Cred%h%Creset (%Cgreen%cn [%G?]%Creset)%Cgreen%d%Creset %s [%Cgreen%cr%Creset]" --graph'
alias gitrlg-nc='git log --pretty=format:"%h (%cn)%d %s [%cr]" --graph'
alias extend_screen='xrandr --output LVDS --mode 1600x900 --pos 0x0 --output HDMI-0 --mode 1920x1080 --pos 1600x0'
alias sudo='nocorrect sudo'
alias .='pwd'
alias keycode="xev | grep -A2 --line-buffered '^KeyRelease' | sed -n '/keycode /s/^.*keycode \([0-9]*\).* (.*, \(.*\)).*$/\1 \2/p'"
alias mpc='mpc -p 6666'
alias sl='/usr/bin/sl'
alias grep='grep -n'
alias archey='cat ~/.archey'
alias mutt="/home/LOG1/Prog/mutt-launcher"
alias newsbeuter="ssh -t 192.168.1.98 newsbeuter"

# Systems vars
export EDITOR=vim
export PATH=$PATH:$HOME/Prog
export PATH=$PATH:/opt/android-sdk/platform-tools/
export PATH=$PATH:$HOME/Prog/android-dev/
export PATH=$PATH:/usr/share/java/apache-ant/bin/
export PATH=$PATH:$HOME/Prog/vimpager
export TERMINAL="st-256color"
export LD_LIBRARY_PATH=$HOME/libs/:$LD_LIBRARY_PATH
export WINEARCH=win32
export DWMABRPATH=/home/LOG1/Log/programmation/c-cpp/x11/dwmabr/bin/Debug/
export DWMFIFOPATH=/home/LOG1/Log/programmation/c-cpp/x11/dwmfifo/dwm/
export MANPAGER="/usr/bin/most -s" # cloured manpage
export MAILDIR="/home/LOG1/mail"
export GPG_TTY=`tty`
export GOPATH="/home/LOG1/Log/programmation/go/"

# XDG vars
export XDG_CONFIG_HOME="/home/LOG1/.config"
export XDG_DATA_HOME="/home/LOG1/.local/share"
export XDG_CACHE_HOME="/home/LOG1/.cache"
export XDG_DOWNLOAD_DIR="/home/LOG1/Download/"

# Launching newsbeuter-listener
pgrep -f newsbeuter-listener.pl > /dev/null || /home/LOG1/Prog/newsbeuter-listener.pl > /dev/null 2>&1 &

# Launching gpg and ssh agents
pgrep gpg-agent > /dev/null || gpg-agent --daemon > /dev/null 2>&1
pgrep ssh-agent > /dev/null || ssh-agent > /tmp/ssh-agent-info-LOG1

source /tmp/gpg-agent-info-LOG1
export GPG_AGENT_INFO
source /tmp/ssh-agent-info-LOG1
export SSH_AUTH_SOCK

# Welcoming
cat /home/LOG1/.archey
archey3 > .archey 2> /dev/null &
remind -w`stty size | cut -d" " -f2` -b1 -cau+ .remind/reminders

